"""remove shedule_id from marks, add judge info

Revision ID: 2ef2b3ebc417
Revises: 48c2dad01dec
Create Date: 2023-12-23 02:27:30.595798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef2b3ebc417'
down_revision: Union[str, None] = '48c2dad01dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('judge_abbreviation', sa.String(length=10), nullable=True))
    op.drop_constraint('marks_shedule_id_fkey', 'marks', type_='foreignkey')
    op.drop_column('marks', 'shedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('shedule_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('marks_shedule_id_fkey', 'marks', 'shedules', ['shedule_id'], ['id'])
    op.drop_column('marks', 'judge_abbreviation')
    # ### end Alembic commands ###
