"""create athlet_coach, competitions tables

Revision ID: caf0279e3f73
Revises: b2e02948a817
Create Date: 2023-12-19 13:17:07.386228

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'caf0279e3f73'
down_revision: Union[str, None] = 'b2e02948a817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('athlet_coach',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('athlet_id', sa.BigInteger(), nullable=False),
    sa.Column('coach_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['athlet_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'couples', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'couples', type_='unique')
    op.drop_table('athlet_coach')
    op.drop_table('competitions')
    # ### end Alembic commands ###
