"""update group table structure

Revision ID: 5ef95a057f41
Revises: 205ccc785acb
Create Date: 2023-12-20 12:07:07.302645

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ef95a057f41'
down_revision: Union[str, None] = '205ccc785acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'competition_judge', ['id'])
    op.create_unique_constraint(None, 'group_participants', ['id'])
    op.alter_column('groups', 'dances',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('groups', 'min_class',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('groups', 'max_class',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.create_unique_constraint(None, 'groups', ['id'])
    op.create_unique_constraint(None, 'marks', ['id'])
    op.create_unique_constraint(None, 'participants', ['id'])
    op.create_unique_constraint(None, 'shedule_judges', ['id'])
    op.create_unique_constraint(None, 'shedules', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shedules', type_='unique')
    op.drop_constraint(None, 'shedule_judges', type_='unique')
    op.drop_constraint(None, 'participants', type_='unique')
    op.drop_constraint(None, 'marks', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    op.alter_column('groups', 'max_class',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('groups', 'min_class',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('groups', 'dances',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'group_participants', type_='unique')
    op.drop_constraint(None, 'competition_judge', type_='unique')
    # ### end Alembic commands ###
